# Generated by Django 5.0.1 on 2024-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockAPI', '0002_dailyprices_csv_file_indexes_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprices',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='indexes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
