# Generated by Django 5.0.1 on 2024-01-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockAPI', '0003_alter_dailyprices_id_alter_indexes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprices',
            name='csv_file',
        ),
    ]
